databases:
  - name: automac-db
    databaseName: automac
    user: automac

services:
  - type: web
    name: automac-web
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "automac-web.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://automac-web.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: automac-db
          property: connectionString
